# Generated by Django 4.2.6 on 2023-10-10 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cart', models.CharField(blank=True, max_length=256)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Category title')),
                ('slug', models.SlugField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Color name')),
                ('hex', models.CharField(max_length=16, verbose_name='Hex color')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Country name')),
                ('slug', models.SlugField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Product title')),
                ('slug', models.SlugField(max_length=16)),
                ('image', models.ImageField(upload_to='', verbose_name='Product image')),
                ('price', models.FloatField(default=0, verbose_name='Product price')),
                ('description', models.TextField(verbose_name='Product description')),
                ('width', models.FloatField(default=0, verbose_name='Width')),
                ('height', models.FloatField(default=0, verbose_name='Height')),
                ('length', models.FloatField(default=0, verbose_name='Length')),
                ('author', models.CharField(max_length=64, verbose_name='Author')),
                ('page_number', models.IntegerField(default=0, verbose_name='Page number')),
                ('stock', models.CharField(choices=[('S', 'In stock'), ('E', 'Ended'), ('D', 'Delivery expected')], max_length=1, verbose_name='Stock')),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Product category')),
                ('color', models.ManyToManyField(to='shop.color', verbose_name='Product colors')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.country', verbose_name='Product country')),
                ('more_image', models.ManyToManyField(blank=True, null=True, to='shop.sliderimage')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=32)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=256)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cart')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.country')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
